### PR TITLE
Add CookieError for error handling

### PR DESCRIPTION
**Pull request by spk**
see https://github.com/alexcrichton/cookie-rs/issues/1
Cheers

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! Could this actually be called `ParseError` as it's returned from `Cookie::parse`. Additionally could it be made into an opaque struct so it can be made extensible in the future as well?

**Comment by spk** [comment]
Glad to help, there is also `percent_decode` that return `std::str::Utf8Error`
I don't know about "opaque struct" I will look it up, thanks

**Comment by alexcrichton** [comment]
Oh sorry by "opaque struct" I mean something like:

```rust
pub struct Error {
    // ... private internals
}
```

vs

```rust
pub enum Error {
    // public variants
}
```

The difference is that with a public enum adding a variant is a breaking change, but with an opaque struct adding fields is not an API-breaking-change.

**Comment by spk** [comment]
Thanks for the explanation ! I've made some changes in 3dcbde55d349010c85b90cc3aee6984820cf3a26

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
