### PR TITLE
chore(cargo): update url to 0.5

### PR DESCRIPTION
**Pull request by untitaker**
~~I also allow 0.2 because it still works with that version~~

### CODE REVIEW

**Comment by untitaker** [comment]
I see, would you accept abandoning Rust 1.0 support in favor of just 1.4?

**Comment by alexcrichton** [comment]
Is there a particularly pressing reason to do this? This isn't a "public dependency" of this crate (e.g. not a shared type), so it should be fine to leave this as-is

**Comment by untitaker** [comment]
No, no particular hurry. Just thought this might be useful because of binary
size.

**Comment by untitaker** [comment]
Updated PR to just pin to latest version.

**Comment by alexcrichton** [comment]
Thanks!

**Comment by SimonSapin** [comment]
Could you get this on crates.io? Thanks!

**Pull request merged**
