### PR TITLE
Added `Clear` method to `CookieJar`.

### PR DESCRIPTION
**Pull request by alexreg**

### CODE REVIEW

**Comment by alexreg** [comment]
Don't know if you want this feature, but I thought I'd make a PR just in case.

**Comment by alexcrichton** [comment]
Thanks! Could you also add a test or two for this?

**Comment by alexreg** [comment]
I amended the 'simple' test. It doesn't test the delta, but nor did it before, so I thought that would be alright. :)

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
