### PR TITLE
Update to rust-url 1.0

### PR DESCRIPTION
**Pull request by SimonSapin**
**Do not merge yet:** rust-url 1.0 is not published yet and may still get breaking changes. The goal of this PR for now is to demonstrate API usage.

Depends on https://github.com/servo/rust-url/pull/176

### CODE REVIEW

**Comment by SimonSapin** [comment]
https://crates.io/crates/url/1.0.0 is (finally!) published, so this is ready to land. Could you also publish it on crates.io?

**Comment by alexcrichton** [comment]
Nice!

**Comment by SimonSapin** [comment]
It realized that this crates only uses percent-encoding. Do you think it would be useful to extract that from the rest of `url` into a separate crate?

**Comment by alexcrichton** [comment]
Perhaps? I'd be fine just leaving the dependency on `url`, not a burning desire of me to slim that down at all

**Pull request merged**
